// AUTO-GENERATED by kernel_manager.py — do not edit by hand.
#include "user_kernels.cuh"

// ---- tiled_transpose (added 2026-02-22T17:03:09) ----
__global__ void tiled_transpose(const float* __restrict__ in,
                                 float* __restrict__ out,
                                 int width)
{
    __shared__ float tile[32][33]; // +1 col to avoid shared memory bank conflicts

    int x = blockIdx.x * 32 + threadIdx.x;
    int y = blockIdx.y * 32 + threadIdx.y;

    if (x < width && y < width)
        tile[threadIdx.y][threadIdx.x] = in[y * width + x];
    __syncthreads();

    x = blockIdx.y * 32 + threadIdx.x;
    y = blockIdx.x * 32 + threadIdx.y;

    if (x < width && y < width)
        out[y * width + x] = tile[threadIdx.x][threadIdx.y];
}

